"""Curated Menschen A1 vocabulary.

Source: the user's personal Wörterbuch (German–Georgian), lesson by lesson.
Georgian dropped; English translations written fresh. OCR artefacts fixed
(e.g. "lhren" -> capitalised forms, "Die schweiz" -> "die Schweiz",
"Bildschirm der" -> "der Bildschirm"). Only single lexical items are kept —
full-sentence phrases ("Wie alt bist du?") are dropped; fixed greeting units
("Guten Tag") are kept because they are learned as single words.

Structure: CHAPTERS maps section number -> (chapter title, description).
VOCAB maps section number -> list of (german, english) tuples.
German nouns always carry their article and are capitalised.
"""

CHAPTERS = {
    1: ("Lektion 1 — Greetings & Introductions", "Saying hello, names, where you're from."),
    2: ("Lektion 2 — Jobs & Professions", "Work, professions, and family status."),
    3: ("Lektion 3 — Family & Furniture", "Relatives, the home, and describing things."),
    5: ("Lektion 5 — Colours, Materials & Objects", "Colours, materials, and everyday objects."),
    6: ("Lektion 6 — Office & Technology", "The workplace, devices, and contact details."),
    7: ("Lektion 7 — Hobbies & Free Time", "Leisure activities and the flea market."),
    8: ("Lektion 8 — Going Out & Times of Day", "Places to go out, days, and times of day."),
    9: ("Lektion 9 — Food & Groceries", "Food, drinks, and meals."),
    10: ("Lektion 10 — Travel & Transport", "Getting around: stations, vehicles, and trips."),
    11: ("Lektion 11 — Daily Life & Time", "Everyday activities and talking about the past."),
    12: (
        "Lektion 12 — Seasons, Months & Celebrations",
        "The calendar, festivals, and travel in the city.",
    ),
    13: ("Lektion 13 — City & Directions", "Places in town and asking the way."),
    14: ("Lektion 14 — Housing & Renting", "Flats, rooms, and renting vocabulary."),
    15: ("Lektion 15 — Neighbourhood", "Your favourite part of town and getting around."),
    16: ("Lektion 16 — Hamburg & Sightseeing", "Landmarks, spices, and cultural events."),
}

# Sections 1–12 -> Menschen A1.1, sections 13–16 -> Menschen A1.2
A1_1_SECTIONS = [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12]
A1_2_SECTIONS = [13, 14, 15, 16]

VOCAB = {
    1: [
        ("der Name", "the name"),
        ("das Lied", "the song"),
        ("die Frau", "the woman / Mrs."),
        ("der Herr", "the gentleman / Mr."),
        ("die Schweiz", "Switzerland"),
        ("Österreich", "Austria"),
        ("aus", "from / out of"),
        ("noch", "still / yet"),
        ("hören", "to hear / to listen"),
        ("sagen", "to say"),
        ("haben", "to have"),
        ("ergänzen", "to complete / to fill in"),
        ("vergleichen", "to compare"),
        ("buchstabieren", "to spell"),
        ("woher", "from where"),
        ("wie", "how"),
        ("wer", "who"),
        ("was", "what"),
        ("welche", "which"),
        ("nein", "no"),
        ("tschüs", "bye"),
        ("Guten Tag", "good day / hello"),
        ("Guten Morgen", "good morning"),
        ("Guten Abend", "good evening"),
        ("Gute Nacht", "good night"),
        ("Auf Wiedersehen", "goodbye"),
    ],
    2: [
        ("der Glaube", "the belief / faith"),
        ("die Journalistin", "the journalist (f.)"),
        ("der Journalist", "the journalist (m.)"),
        ("der Beruf", "the profession / job"),
        ("die Friseurin", "the hairdresser (f.)"),
        ("die Ausbildung", "the (vocational) training"),
        ("das Kind", "the child"),
        ("das Alter", "the age"),
        ("der Wohnort", "the place of residence"),
        ("die Herkunft", "the origin"),
        ("der Arbeitgeber", "the employer"),
        ("die Kellnerin", "the waitress"),
        ("der Familienstand", "the marital status"),
        ("die Begrüßung", "the greeting"),
        ("der Abschied", "the farewell"),
        ("das Land", "the country"),
        ("das Befinden", "the state of health / how one feels"),
        ("die Hochschule", "the university / college"),
        ("die Schule", "the school"),
        ("die Stelle", "the position / job"),
        ("der Architekt", "the architect"),
        ("der Arzt", "the doctor"),
        ("der Ingenieur", "the engineer"),
        ("die Krankenschwester", "the nurse"),
        ("der Lehrer", "the teacher"),
        ("der Student", "the student"),
        ("der Schauspieler", "the actor"),
        ("der Schüler", "the pupil"),
        ("der Sekretär", "the secretary"),
        ("der Verkäufer", "the salesman"),
        ("sehen", "to see"),
        ("schreiben", "to write"),
        ("machen", "to do / to make"),
        ("leben", "to live"),
        ("studieren", "to study"),
        ("übersetzen", "to translate"),
        ("glauben", "to believe"),
        ("verheiratet", "married"),
        ("geschieden", "divorced"),
        ("arbeitslos", "unemployed"),
        ("zusammen", "together"),
        ("allein", "alone"),
        ("wichtig", "important"),
        ("weitere", "further / additional"),
        ("richtig", "correct / right"),
        ("falsch", "wrong / false"),
    ],
    3: [
        ("die Mutter", "the mother"),
        ("der Vater", "the father"),
        ("die Eltern", "the parents"),
        ("die Geschwister", "the siblings"),
        ("die Großeltern", "the grandparents"),
        ("die Großmutter", "the grandmother"),
        ("der Großvater", "the grandfather"),
        ("die Enkelin", "the granddaughter"),
        ("der Ehemann", "the husband"),
        ("die Ehefrau", "the wife"),
        ("die Familie", "the family"),
        ("die Tochter", "the daughter"),
        ("der Freund", "the friend / boyfriend"),
        ("der Kollege", "the colleague"),
        ("der Partner", "the partner"),
        ("die Rentnerin", "the pensioner (f.)"),
        ("die Nichte", "the niece"),
        ("der Neffe", "the nephew"),
        ("der Stammbaum", "the family tree"),
        ("die Sprache", "the language"),
        ("die Fremdsprache", "the foreign language"),
        ("das Bild", "the picture"),
        ("die Heimatstadt", "the home town"),
        ("der Sänger", "the singer"),
        ("das Sternzeichen", "the star sign"),
        ("der Stern", "the star"),
        ("Griechenland", "Greece"),
        ("Französisch", "French (language)"),
        ("die Möbel", "the furniture"),
        ("das Bett", "the bed"),
        ("die Lampe", "the lamp"),
        ("der Schrank", "the cupboard / wardrobe"),
        ("der Sessel", "the armchair"),
        ("das Sofa", "the sofa"),
        ("der Stuhl", "the chair"),
        ("der Teppich", "the carpet"),
        ("der Tisch", "the table"),
        ("die Couch", "the couch"),
        ("der Euro", "the euro"),
        ("der Cent", "the cent"),
        ("der Preis", "the price"),
        ("das Angebot", "the offer"),
        ("das Sonderangebot", "the special offer"),
        ("die Hilfe", "the help"),
        ("das Zimmer", "the room"),
        ("der Hund", "the dog"),
        ("die Ferien", "the holidays / vacation"),
        ("die Zeitung", "the newspaper"),
        ("singen", "to sing"),
        ("kochen", "to cook"),
        ("beschreiben", "to describe"),
        ("brauchen", "to need"),
        ("finden", "to find"),
        ("fragen", "to ask"),
        ("denken", "to think"),
        ("wissen", "to know (a fact)"),
        ("gehen", "to go"),
        ("füttern", "to feed (an animal)"),
        ("bellen", "to bark"),
        ("fliegen", "to fly"),
        ("groß", "big / tall"),
        ("klein", "small"),
        ("hässlich", "ugly"),
        ("kurz", "short"),
        ("lang", "long"),
        ("leicht", "easy / light"),
        ("schwer", "heavy / difficult"),
        ("modern", "modern"),
        ("praktisch", "practical"),
        ("schlecht", "bad"),
        ("schön", "beautiful / nice"),
        ("günstig", "cheap / good value"),
        ("billig", "cheap"),
        ("teuer", "expensive"),
        ("toll", "great"),
        ("genau", "exactly"),
        ("schon", "already"),
        ("nur", "only"),
        ("viele", "many"),
        ("jetzt", "now"),
        ("bald", "soon"),
        ("fertig", "ready / finished"),
        ("zurück", "back"),
        ("wieder", "again"),
        ("wirklich", "really"),
        ("aber", "but"),
    ],
    5: [
        ("die Aufgabe", "the task / exercise"),
        ("der Kaffee", "the coffee"),
        ("das Geschenk", "the present / gift"),
        ("die Lösung", "the solution"),
        ("das Geld", "the money"),
        ("der Gruß", "the greeting"),
        ("der Tipp", "the tip / hint"),
        ("der Kunststoff", "the plastic / synthetic material"),
        ("die Farbe", "the colour"),
        ("die Brille", "the glasses"),
        ("der Frühling", "the spring"),
        ("das Glas", "the glass"),
        ("das Gestell", "the frame / rack"),
        ("das Material", "the material"),
        ("das Holz", "the wood"),
        ("das Metall", "the metal"),
        ("das Papier", "the paper"),
        ("das Plastik", "the plastic"),
        ("der Bleistift", "the pencil"),
        ("das Buch", "the book"),
        ("das Feuerzeug", "the lighter"),
        ("die Flasche", "the bottle"),
        ("der Fotoapparat", "the camera"),
        ("die Geldbörse", "the wallet / purse"),
        ("die Kette", "the chain / necklace"),
        ("der Kugelschreiber", "the ballpoint pen"),
        ("der Regenschirm", "the umbrella"),
        ("der Ring", "the ring"),
        ("der Schlüssel", "the key"),
        ("die Seife", "the soap"),
        ("das Streichholz", "the match"),
        ("die Tasche", "the bag"),
        ("die Uhr", "the clock / watch"),
        ("die Adresse", "the address"),
        ("die E-Mail", "the email"),
        ("das Fax", "the fax"),
        ("das Geburtsdatum", "the date of birth"),
        ("die Hausnummer", "the house number"),
        ("die Nummer", "the number"),
        ("der Ort", "the place / town"),
        ("die Straße", "the street"),
        ("das Telefon", "the telephone"),
        ("die Entschuldigung", "the apology / excuse"),
        ("die Menge", "the amount / crowd"),
        ("das Problem", "the problem"),
        ("das Produkt", "the product"),
        ("das Wort", "the word"),
        ("das Wörterbuch", "the dictionary"),
        ("verkaufen", "to sell"),
        ("bekommen", "to get / receive"),
        ("bieten", "to offer"),
        ("schwarz", "black"),
        ("weiß", "white"),
        ("blau", "blue"),
        ("braun", "brown"),
        ("gelb", "yellow"),
        ("rot", "red"),
        ("orange", "orange"),
        ("grün", "green"),
        ("rund", "round"),
        ("eckig", "angular / square"),
        ("dunkel", "dark"),
        ("neu", "new"),
        ("verschieden", "different / various"),
        ("ohne", "without"),
        ("unter", "under"),
    ],
    6: [
        ("der Arbeitsplatz", "the workplace"),
        ("die Briefmarke", "the stamp"),
        ("das Büro", "the office"),
        ("der Chef", "the boss"),
        ("der Computer", "the computer"),
        ("der Drucker", "the printer"),
        ("die Firma", "the company"),
        ("das Formular", "the form"),
        ("das Handy", "the mobile phone"),
        ("der Kalender", "the calendar"),
        ("der Laptop", "the laptop"),
        ("die Maus", "the mouse"),
        ("das Notizbuch", "the notebook"),
        ("die Rechnung", "the bill / invoice"),
        ("die SMS", "the text message"),
        ("der Termin", "the appointment"),
        ("das Foto", "the photo"),
        ("der See", "the lake"),
        ("der Stress", "the stress"),
        ("die Telefonnummer", "the phone number"),
        ("der Bildschirm", "the screen"),
        ("suchen", "to look for / search"),
        ("heute", "today"),
        ("hier", "here"),
    ],
    7: [
        ("der Ausflug", "the excursion / trip"),
        ("der Film", "the film / movie"),
        ("die Freizeit", "the free time"),
        ("das Hobby", "the hobby"),
        ("das Kino", "the cinema"),
        ("die Musik", "the music"),
        ("das Auto", "the car"),
        ("das Gespräch", "the conversation"),
        ("das Internet", "the internet"),
        ("die Natur", "nature"),
        ("der Stift", "the pen"),
        ("das Stück", "the piece"),
        ("der Autor", "the author"),
        ("der Süden", "the south"),
        ("der Norden", "the north"),
        ("der Westen", "the west"),
        ("der Osten", "the east"),
        ("der Trödelmarkt", "the flea market"),
        ("der Händler", "the trader / dealer"),
        ("der Besucher", "the visitor"),
        ("die Kleidung", "the clothing"),
        ("die Tierklinik", "the animal clinic"),
        ("das Tier", "the animal"),
        ("der Eintritt", "the entry / admission"),
        ("backen", "to bake"),
        ("besuchen", "to visit"),
        ("treffen", "to meet"),
        ("fotografieren", "to take photos"),
        ("lesen", "to read"),
        ("lieben", "to love"),
        ("malen", "to paint"),
        ("schwimmen", "to swim"),
        ("spielen", "to play"),
        ("tanzen", "to dance"),
        ("rauchen", "to smoke"),
        ("können", "to be able to / can"),
        ("stöbern", "to browse / rummage"),
        ("handeln", "to bargain / to trade"),
        ("öffnen", "to open"),
        ("oft", "often"),
        ("nie", "never"),
        ("klar", "clear / of course"),
        ("natürlich", "naturally / of course"),
        ("leider", "unfortunately"),
        ("hübsch", "pretty"),
        ("einfach", "simple / simply"),
        ("gern", "gladly / with pleasure"),
        ("alles", "everything"),
        ("zwischen", "between"),
        ("an", "at / on"),
    ],
    8: [
        ("die Ausstellung", "the exhibition"),
        ("die Bar", "the bar"),
        ("das Café", "the café"),
        ("die Disco", "the disco"),
        ("die Kneipe", "the pub"),
        ("das Konzert", "the concert"),
        ("das Museum", "the museum"),
        ("das Restaurant", "the restaurant"),
        ("das Schwimmbad", "the swimming pool"),
        ("das Theater", "the theatre"),
        ("die Tageszeit", "the time of day"),
        ("der Morgen", "the morning"),
        ("der Vormittag", "the late morning"),
        ("der Mittag", "midday / noon"),
        ("der Nachmittag", "the afternoon"),
        ("der Abend", "the evening"),
        ("die Nacht", "the night"),
        ("die Liebe", "love"),
        ("der Tag", "the day"),
        ("die Woche", "the week"),
        ("der Montag", "Monday"),
        ("der Dienstag", "Tuesday"),
        ("der Mittwoch", "Wednesday"),
        ("der Donnerstag", "Thursday"),
        ("der Freitag", "Friday"),
        ("der Samstag", "Saturday"),
        ("der Sonntag", "Sunday"),
        ("das Essen", "the food / meal"),
        ("das Fernsehen", "television"),
        ("das Radio", "the radio"),
        ("das Wissen", "knowledge"),
        ("die Idee", "the idea"),
        ("lieber", "rather / preferably"),
        ("besonders", "especially"),
        ("höflich", "polite"),
        ("unhöflich", "impolite"),
        ("morgen", "tomorrow"),
        ("spät", "late"),
        ("vielleicht", "maybe"),
    ],
    9: [
        ("die Lebensmittel", "the groceries / food"),
        ("der Apfel", "the apple"),
        ("der Braten", "the roast"),
        ("das Brötchen", "the bread roll"),
        ("das Brot", "the bread"),
        ("die Butter", "the butter"),
        ("das Ei", "the egg"),
        ("das Eis", "the ice cream"),
        ("der Fisch", "the fish"),
        ("das Fleisch", "the meat"),
        ("der Käse", "the cheese"),
        ("die Kartoffel", "the potato"),
        ("der Kuchen", "the cake"),
        ("die Milch", "the milk"),
        ("das Obst", "the fruit"),
        ("die Orange", "the orange"),
        ("der Reis", "the rice"),
        ("die Sahne", "the cream"),
        ("der Salat", "the salad / lettuce"),
        ("der Schinken", "the ham"),
        ("die Schokolade", "the chocolate"),
        ("die Suppe", "the soup"),
        ("der Tee", "the tea"),
        ("die Tomate", "the tomato"),
        ("die Wurst", "the sausage"),
        ("die Zitrone", "the lemon"),
        ("die Zwiebel", "the onion"),
        ("der Durst", "the thirst"),
        ("das Frühstück", "the breakfast"),
        ("der Hunger", "the hunger"),
        ("der Kühlschrank", "the fridge"),
        ("die Einladung", "the invitation"),
        ("die Speisekarte", "the menu"),
        ("das Wochenende", "the weekend"),
        ("die Vorspeise", "the starter"),
        ("das Hauptgericht", "the main course"),
        ("der Rest", "the rest / leftover"),
        ("das Rindfleisch", "the beef"),
        ("der Pfeffer", "the pepper"),
        ("die Gurke", "the cucumber"),
        ("die Zutat", "the ingredient"),
        ("frühstücken", "to have breakfast"),
        ("schmecken", "to taste"),
        ("trinken", "to drink"),
        ("kennen", "to know (be familiar with)"),
        ("würzen", "to season"),
        ("verwenden", "to use"),
        ("bedeuten", "to mean"),
        ("frisch", "fresh"),
        ("selbst", "oneself / by oneself"),
        ("etwas", "something"),
        ("erst", "first / only (time)"),
        ("ganz", "whole / completely"),
        ("früher", "earlier / in the past"),
    ],
    10: [
        ("der Bahnhof", "the train station"),
        ("der Bahnsteig", "the platform"),
        ("der Bus", "the bus"),
        ("der Halt", "the stop"),
        ("die Haltestelle", "the (bus/tram) stop"),
        ("der Flughafen", "the airport"),
        ("das Flugzeug", "the aeroplane"),
        ("das Gepäck", "the luggage"),
        ("das Gleis", "the track / platform"),
        ("der Koffer", "the suitcase"),
        ("die S-Bahn", "the city train"),
        ("die Straßenbahn", "the tram"),
        ("die Tram", "the tram"),
        ("das Taxi", "the taxi"),
        ("die U-Bahn", "the underground / metro"),
        ("das Verkehrsmittel", "the means of transport"),
        ("der Zug", "the train"),
        ("die Minute", "the minute"),
        ("die Vorsicht", "the caution"),
        ("abfahren", "to depart"),
        ("abholen", "to pick up / collect"),
        ("ankommen", "to arrive"),
        ("aussteigen", "to get off"),
        ("einsteigen", "to get on / board"),
        ("umsteigen", "to change (trains)"),
        ("anrufen", "to call (on the phone)"),
        ("einkaufen", "to go shopping"),
        ("fernsehen", "to watch TV"),
        ("mitbringen", "to bring along"),
        ("nehmen", "to take"),
        ("gerade", "just / straight"),
        ("nächste", "next"),
    ],
    11: [
        ("die Arbeit", "the work / job"),
        ("die Hausaufgabe", "the homework"),
        ("die Pause", "the break"),
        ("das Baby", "the baby"),
        ("das Fahrrad", "the bicycle"),
        ("der Monat", "the month"),
        ("das Paar", "the pair / couple"),
        ("die Party", "the party"),
        ("die Reise", "the journey / trip"),
        ("der Sport", "the sport"),
        ("der Wein", "the wine"),
        ("aufräumen", "to tidy up"),
        ("einladen", "to invite"),
        ("lachen", "to laugh"),
        ("lernen", "to learn"),
        ("reden", "to talk"),
        ("schlafen", "to sleep"),
        ("meinen", "to mean / to think"),
        ("täglich", "daily"),
        ("interessant", "interesting"),
        ("lange", "(for) a long time"),
        ("langweilig", "boring"),
        ("letzt", "last"),
        ("schwanger", "pregnant"),
    ],
    12: [
        ("der Sommer", "the summer"),
        ("der Herbst", "the autumn"),
        ("der Winter", "the winter"),
        ("der Januar", "January"),
        ("der Februar", "February"),
        ("der März", "March"),
        ("der April", "April"),
        ("der Mai", "May"),
        ("der Juni", "June"),
        ("der Juli", "July"),
        ("der August", "August"),
        ("der September", "September"),
        ("der Oktober", "October"),
        ("der November", "November"),
        ("der Dezember", "December"),
        ("das Fest", "the festival / celebration"),
        ("die Hochzeit", "the wedding"),
        ("der Karneval", "the carnival"),
        ("das Neujahr", "New Year"),
        ("das Silvester", "New Year's Eve"),
        ("das Bier", "the beer"),
        ("die Leute", "the people"),
        ("die Person", "the person"),
        ("das Schwein", "the pig"),
        ("die Bahn", "the train / railway"),
        ("der Schatz", "the treasure / darling"),
        ("die Aussicht", "the view"),
        ("der Mensch", "the human / person"),
        ("anfangen", "to begin"),
        ("aufhören", "to stop"),
        ("feiern", "to celebrate"),
        ("dauern", "to last"),
        ("gefallen", "to please / to like"),
        ("geben", "to give"),
        ("springen", "to jump"),
        ("üben", "to practise"),
        ("besichtigen", "to visit / tour"),
        ("genießen", "to enjoy"),
        ("gestern", "yesterday"),
        ("fleißig", "hard-working / diligent"),
        ("glücklich", "happy"),
        ("schnell", "fast"),
        ("bequem", "comfortable"),
        ("wenig", "little / few"),
    ],
    13: [
        ("die Ampel", "the traffic light"),
        ("die Bank", "the bank / bench"),
        ("die Brücke", "the bridge"),
        ("der Dom", "the cathedral"),
        ("das Hotel", "the hotel"),
        ("die Mitte", "the middle / centre"),
        ("die Stadtmitte", "the town centre"),
        ("der Plan", "the plan"),
        ("der Stadtplan", "the city map"),
        ("die Polizei", "the police"),
        ("die Post", "the post office"),
        ("das Zentrum", "the centre"),
        ("der Kilometer", "the kilometre"),
        ("der Meter", "the metre"),
        ("die Nähe", "the vicinity / nearness"),
        ("der Weg", "the way / path"),
        ("die Frage", "the question"),
        ("der Moment", "the moment"),
        ("abbiegen", "to turn off"),
        ("weiterfahren", "to drive on"),
        ("wenden", "to turn around"),
        ("zurückfahren", "to drive back"),
        ("helfen", "to help"),
        ("stimmen", "to be correct"),
        ("fremd", "foreign / unfamiliar"),
        ("links", "left"),
        ("rechts", "right"),
        ("nett", "nice / kind"),
        ("beide", "both"),
        ("in", "in"),
        ("auf", "on"),
        ("über", "over / above"),
        ("vor", "in front of / before"),
        ("hinter", "behind"),
        ("neben", "next to"),
    ],
    14: [
        ("die Tiefgarage", "the underground car park"),
        ("der Stellplatz", "the parking space"),
        ("der Aufzug", "the lift / elevator"),
        ("die Nebenkosten", "the additional costs"),
        ("die Polizistin", "the police officer (f.)"),
        ("der Herd", "the stove / cooker"),
        ("der Raum", "the room / space"),
        ("der Wohnpark", "the residential complex"),
        ("die Warmmiete", "the rent including bills"),
        ("die Kaltmiete", "the rent excluding bills"),
        ("das Beispiel", "the example"),
        ("eigen", "own"),
        ("sofort", "immediately"),
        ("frei", "free / available"),
        ("dringend", "urgent"),
        ("inklusive", "inclusive / included"),
        ("circa", "approximately"),
    ],
    15: [
        ("das Lieblingsviertel", "the favourite neighbourhood"),
        ("die Werkstatt", "the workshop"),
        ("der Fuß", "the foot"),
        ("gehören", "to belong"),
        ("hingehen", "to go (there)"),
        ("gratulieren", "to congratulate"),
        ("überall", "everywhere"),
        ("nämlich", "namely / you see"),
        ("andere", "other"),
    ],
    16: [
        ("die Speicherstadt", "the warehouse district"),
        ("das Gewürz", "the spice"),
        ("die Lesung", "the (book) reading"),
        ("die Theateraufführung", "the theatre performance"),
        ("das Wahrzeichen", "the landmark"),
        ("lagern", "to store"),
        ("unbedingt", "definitely / absolutely"),
    ],
}
