# Generated by Django 6.0.6 on 2026-06-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_reviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordprogress',
            name='lapses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordprogress',
            name='times_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordprogress',
            name='times_seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordprogress',
            name='times_wrong',
            field=models.IntegerField(default=0),
        ),
    ]
