# Generated by Django 5.2.15 on 2026-06-19 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_wordprogress_lapses_wordprogress_times_correct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordprogress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordprogress',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='vocabulary.word'),
        ),
        migrations.AlterUniqueTogether(
            name='wordprogress',
            unique_together={('user', 'word')},
        ),
    ]
