# Generated by Django 6.0.6 on 2026-06-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='exercise',
            name='source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='correct_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('translation', 'Translate to German'), ('fill_blank', 'Fill in the Blank'), ('article', 'Choose Correct Article'), ('conjugation', 'Conjugate the Verb'), ('free_text', 'Free Text Answer'), ('multiple_choice', 'Multiple Choice'), ('matching', 'Match Pairs'), ('sentence_order', 'Put Words in Order'), ('word_bank', 'Fill Blanks from a Word Bank')], max_length=50),
        ),
    ]
