# Generated by Django 5.2.15 on 2026-07-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_seed_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsuggestion',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
