# Generated by Django 5.2.15 on 2026-07-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_historylesson_cefr_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylesson',
            name='excerpt',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='historylesson',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
