# Generated by Django 5.2.15 on 2026-06-22 13:31

from django.db import migrations, models


def mark_existing_complete(apps, schema_editor):
    """Existing accounts (e.g. the superuser) already have a username + password,
    so they're considered onboarded — only new social signups start incomplete."""
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserProfile.objects.update(profile_complete=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_avatar_url_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_complete, migrations.RunPython.noop),
    ]
