# Generated by Django 5.2.15 on 2026-06-08 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('articles', 'Articles (der/die/das)'), ('cases', 'Cases (Nominativ, Akkusativ, etc.)'), ('verbs', 'Verbs & Conjugation'), ('sentence_structure', 'Sentence Structure'), ('pronouns', 'Pronouns'), ('adjectives', 'Adjectives'), ('other', 'Other')], default='other', max_length=50)),
                ('content', models.TextField()),
                ('example_sentences', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_rules', to='books.chapter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
